### ISSUE TITLE
Linux x64 - Crash on startup in Ubuntu 14.04 using versions 1.0 to 1.4

### ISSUE THREAD

**Issue by bchauvin** [mawie81/whatsdesktop#3]
Using linux x64 build in Ubuntu 14.04, WhatsDestop crashes on startup. 
This problem has been introduced in WhatsDesktop 1.0 and further, since version 0.1 works fine.

Stack below:

Uncaught Exception:
TypeError: Error processing argument -1.
    at TypeError (native)
    at createTray (/home/bert/Downloads/WhatsDesktop-linux-1.0.0/resources/app/index.js:71:13)
    at EventEmitter.<anonymous> (/home/bert/Downloads/WhatsDesktop-linux-1.0.0/resources/app/index.js:84:3)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)

Uncaught Exception:
TypeError: Cannot read property 'setImage' of undefined
    at updateBadge (/home/bert/Downloads/WhatsDesktop-linux-1.0.0/resources/app/index.js:32:12)
    at BrowserWindow.<anonymous> (/home/bert/Downloads/WhatsDesktop-linux-1.0.0/resources/app/index.js:59:45)
    at emitTwo (events.js:87:13)
    at BrowserWindow.emit (events.js:172:7)

**Comment by mawie81** [comment]
Thanks for reporting 😀
I just pushed a new release that should fix it.

**Comment by bchauvin** [comment]
Hi,
Thank your for fixing it so quickly, that's very much appreciated !
It works perfectly fine now, really happy with it :-)
